# Generated by Django 2.2.12 on 2022-10-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200725_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='updated_on',
            new_name='last_updated',
        ),
        migrations.DeleteModel(
            name='UserAuthentication',
        ),
    ]
